# tests/e2e/service_worker.py — the worker is the whole offline story: precache the shell,
# never touch another project's caches, and keep working with the network gone.
#
# A copy of the root suite. Five kinds of change and no others:
#   · the module token — the seed goes through `window.__zajilDb`, because the port's data
#     layer is bundled and reachable only from the harness route;
#   · the DOM tokens — `.bird-row` -> `[data-testid=bird-row]`, and
#     `.coi-headline .coi-badge` -> `[data-testid=coi-headline] [data-testid=coi-badge]`.
#     The desktop table's `[data-testid=table-row]` is ALWAYS in the DOM (responsive
#     selection is CSS-only), so the phone list is what gets counted;
#   · the routes — `#/pedigree/<id>` -> `pedigree/?id=<id>`;
#   · `wait_until='load'` throughout, never 'networkidle': a page controlled by a service
#     worker never goes idle (HANDOFF.md:100-106);
#   · it provisions its own server (R6). The root suite assumes a hand-started one on 8123,
#     which is the class of defect RF-1 records.
#
# The two things this suite is really guarding are both about NOT breaking someone else:
# the sibling-cache seed, and the fact that a failed install leaves no cache at all.
import os
import sys
import uuid as _uuid

from playwright.sync_api import sync_playwright

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'sync'))
from _serve import serve                      # noqa: E402

# The shipped datasets carry real uuids (v1.9.1). Python's uuid5 derives exactly what
# tools/idmap.js derives from the same namespace and key, so these suites keep naming birds
# by the readable key that documents what they are.
_ID_NS = _uuid.UUID('7f3c9a54-2b18-4d6e-9c05-1a2b3c4d5e6f')
def bird_id(key):
    return str(_uuid.uuid5(_ID_NS, key))

ok = fail = 0
def check(n, c, e=''):
    global ok, fail
    if c: ok += 1; print(f'  ✓ {n}')
    else: fail += 1; print(f'  ✗ {n} {e}')

OUT = os.path.abspath(os.path.join(HERE, '..', '..', 'out'))
if not os.path.exists(os.path.join(OUT, 'sw.js')):
    print('  NOT RUN — out/sw.js is missing. The worker is generated by the build'
          ' (scripts/build-sw.mjs); run `npm run build:harness` first.')
    print('  0 passed, 0 failed  (nothing was checked)')
    raise SystemExit(2)

srv, HARNESS = serve()
ROOT = HARNESS.replace('test-harness/', '')

try:
    with sync_playwright() as p:
        b = p.chromium.launch(); ctx = b.new_context(); page = ctx.new_page()
        page.set_default_timeout(30000)
        errs = []; page.on('pageerror', lambda e: errs.append(str(e)))

        # seed a SIBLING project's cache on the same origin, as github.io would have
        page.goto(ROOT + 'birds/', wait_until='load'); page.wait_for_timeout(500)
        page.evaluate("async () => { const c = await caches.open('other-project-v1'); await c.put('/sibling', new Response('x')); }")
        page.wait_for_timeout(2500)  # let our SW install/activate
        names = page.evaluate("async () => await caches.keys()")
        check("sibling project's cache survived our activate", 'other-project-v1' in names, str(names))
        check('our versioned cache exists', any(n.startswith('zajil-') for n in names), str(names))

        # …and the install really completed: an atomic addAll that hit a single 404 would
        # leave the cache EMPTY, which looks identical to "not activated yet" from outside
        entries = page.evaluate("""async () => {
            const k = (await caches.keys()).find(n => n.startsWith('zajil-'));
            if (!k) return -1;
            return (await (await caches.open(k)).keys()).length;
        }""")
        check('…and the precache is populated, not an empty shell from a failed addAll',
              entries > 50, str(entries))

        # the harness route seeds the loft; the shipped shell has no way in
        seed = ctx.new_page()
        seed.goto(HARNESS, wait_until='load'); seed.wait_for_timeout(800)
        seed.evaluate("async () => { await window.__zajilReady; }")
        seed.evaluate("""async () => { const db = await window.__zajilDb;
            await db.importAll(await (await fetch(new URL('example-loft-large.json', document.querySelector('link[rel=manifest]').href))).json(), 'merge'); }""")
        seed.close()
        page.wait_for_timeout(500)

        ctx.set_offline(True)
        page.reload(wait_until='load'); page.wait_for_timeout(1800)
        check('OFFLINE still works after SW changes', page.locator('[data-testid=bird-row]').count() == 38,
              str(page.locator('[data-testid=bird-row]').count()))

        page.goto(ROOT + 'pedigree/?id=' + bird_id('g5-faris26'), wait_until='load')
        page.wait_for_timeout(1800)
        check('OFFLINE pedigree + COI',
              '12.5' in page.locator('[data-testid=coi-headline] [data-testid=coi-badge]').inner_text(),
              page.locator('[data-testid=coi-headline]').inner_text().replace('\n', ' ')[:80])

        # [port] the flat export means a clean URL is a different request from the file the
        # cache holds, so the navigation fallback has to resolve it — and it must resolve to
        # the RIGHT document, not to index.html, which is a redirect to /birds
        page.goto(ROOT + 'stats', wait_until='load'); page.wait_for_timeout(1500)
        check('OFFLINE a clean URL with no .html still finds its OWN document',
              page.locator('[data-testid=count-line]').count() == 1
              and page.locator('[data-testid=bird-row]').count() == 0,
              page.url.split('/')[-1])

        # [port] and a route that was never built falls back to the shell rather than dying
        page.goto(ROOT + 'no-such-route', wait_until='load'); page.wait_for_timeout(1500)
        check('OFFLINE an unknown route falls back to the shell instead of failing',
              'زاجل' in page.title(), page.title())

        # [port] A harness build precaches its own route. Leaving it out meant an offline
        # reload of the harness page fell through to index.html and rendered the WRONG
        # document — green about the wrong page, which is worse than an error.
        page.goto(HARNESS, wait_until='load'); page.wait_for_timeout(1800)
        check('OFFLINE the harness route serves the HARNESS, not the shell',
              page.evaluate("() => typeof window.__zajilReady !== 'undefined'"),
              page.url.split('/')[-1])

        ctx.set_offline(False)
        check('zero page errors', not errs, '; '.join(errs[:2]))

        # ── [departure 3] the install split, proved both ways ───────────────────────────
        # Vanilla's addAll is atomic over 41 hand-checked paths. This list is ~130
        # build-named ones, about half of them RSC payloads that only affect client-side
        # navigation, so keeping the whole thing atomic would mean one 404 on one payload
        # costs the app its entire offline mode. The shell stays atomic; the payloads do
        # not. Both halves are asserted, because either one silently reverting looks fine.
        def cache_entries(pg):
            return pg.evaluate("""async () => { const k = (await caches.keys()).find(x => x.startsWith('zajil-'));
                return k ? (await (await caches.open(k)).keys()).length : -1; }""")

        opt = b.new_context()
        opt.route('**/stats.txt', lambda route: route.fulfill(status=404, body=''))
        op = opt.new_page(); operrs = []; op.on('pageerror', lambda e: operrs.append(str(e)))
        op.goto(ROOT + 'birds/', wait_until='load'); op.wait_for_timeout(4000)
        n_opt = cache_entries(op)
        opt.set_offline(True)
        op.reload(wait_until='load'); op.wait_for_timeout(1800)
        check('[departure 3] a navigation payload that 404s costs its own route, not the whole cache',
              n_opt > 50 and 'زاجل' in op.title(), f'{n_opt} entries, title {op.title()!r}')
        check('…and nothing was raised at the page about it', not operrs, '; '.join(operrs[:2]))
        opt.close()

        crit = b.new_context()
        crit.route('**/sample-data.json', lambda route: route.fulfill(status=404, body=''))
        cp = crit.new_page()
        cp.goto(ROOT + 'birds/', wait_until='load'); cp.wait_for_timeout(4000)
        n_crit = cache_entries(cp)
        check('[departure 3] …while a missing SHELL entry still fails the install atomically, as vanilla does',
              n_crit <= 0, f'{n_crit} entries — a half-installed shell is worse than none')
        crit.close()

        b.close()
finally:
    srv.terminate()

print(f'\n{ok} passed, {fail} failed')
raise SystemExit(1 if fail else 0)
