# tests/e2e/version_display.py — the About row reports what the SERVICE WORKER says is
# installed, never a constant compiled into the bundle. Those two disagree exactly when it
# matters: when an update has been fetched but has not activated yet.
#
# A copy of the root suite. Four kinds of change and no others:
#   · the module/DOM tokens — `.about-version` -> `[data-testid=about-version]`;
#   · the route — `#/tools` -> `tools.html`;
#   · the version source — the worker is a BUILD PRODUCT here (out/sw.js, generated by
#     scripts/build-sw.mjs from sw/sw.template.js), because the precache list cannot be
#     written by hand against content-hashed filenames and because next/'s
#     no-hardcoded-version guard forbids the literal in source. The suite reads the
#     version out of the generated worker, exactly as the root reads it out of sw.js —
#     still from source, still never hardcoded here;
#   · #8's file list — the port has no js/ directory, so the check becomes what the guard
#     enforces: no SHIPPED chunk carries the version string. That is a stronger claim than
#     the root's four-file spot check, and it is asserted against the real export.
#
# Provisions its own server (R6): the root suite assumes a hand-started one on 8123.
import os
import re
import sys

from playwright.sync_api import sync_playwright

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'sync'))
from _serve import serve                      # noqa: E402

ok = fail = 0
def check(n, c, e=''):
    global ok, fail
    if c: ok += 1; print(f'  ✓ {n}')
    else: fail += 1; print(f'  ✗ {n} {e}')

OUT = os.path.abspath(os.path.join(HERE, '..', '..', 'out'))
SW_SRC = os.path.join(OUT, 'sw.js')
if not os.path.exists(SW_SRC):
    print('  NOT RUN — out/sw.js is missing. The worker is generated by the build'
          ' (scripts/build-sw.mjs); run `npm run build:harness` first.')
    print('  0 passed, 0 failed  (nothing was checked)')
    raise SystemExit(2)

# the value the SW should report, read from the worker's own source — the test must not
# hardcode it. Anchored at a line start: the file's prose must not be able to answer.
_m = re.search(r"^const VERSION = '([^']+)'", open(SW_SRC, encoding='utf-8').read(), re.M)
if not _m:
    print("  NOT RUN — out/sw.js has no top-level VERSION constant to read")
    print('  0 passed, 0 failed  (nothing was checked)')
    raise SystemExit(2)
SW_VERSION = _m.group(1)

srv, HARNESS = serve()
ROOT = HARNESS.replace('test-harness.html', '')

try:
    with sync_playwright() as p:
        br = p.chromium.launch()
        ctx = br.new_context()
        page = ctx.new_page(); page.set_default_timeout(25000)
        errs = []; page.on('pageerror', lambda e: errs.append(str(e)))
        # a service worker needs a secure context; 127.0.0.1 counts as one
        page.goto(ROOT + 'birds.html', wait_until='load'); page.wait_for_timeout(2500)
        page.evaluate("() => navigator.serviceWorker.ready")
        page.reload(wait_until='load'); page.wait_for_timeout(2000)   # ensure a CONTROLLER exists

        controlled = page.evaluate("() => !!navigator.serviceWorker.controller")
        check('the page is controlled by a service worker', controlled)

        page.goto(ROOT + 'tools.html', wait_until='load'); page.wait_for_timeout(2500)
        row = page.locator('[data-testid=about-version]')
        check('Settings renders an About version row', row.count() == 1, str(row.count()))
        shown = row.inner_text().strip()
        check('the row is never blank', shown != '', repr(shown))

        # THE POINT: it must equal what the live SW reports, not a constant in the bundle
        reported = page.evaluate("""async () => {
            const sw = navigator.serviceWorker.controller;
            if (!sw) return null;
            return await new Promise((resolve) => {
                const ch = new MessageChannel();
                const t = setTimeout(() => resolve(null), 3000);
                ch.port1.onmessage = (e) => { clearTimeout(t); resolve(e.data && e.data.version); };
                sw.postMessage({ type: 'GET_VERSION' }, [ch.port2]);
            });
        }""")
        check('the SW answers a GET_VERSION message', reported is not None, str(reported))
        check('the SW reports the version in sw.js source', reported == SW_VERSION, f'{reported} vs {SW_VERSION}')
        check('the displayed string contains that exact version', reported in shown, f'{shown!r} lacks {reported!r}')
        check('it is not the unknown fallback', 'غير معروف' not in shown, shown)

        # No SHIPPED file may carry the app version — the screen must ask the worker. The
        # root spot-checks four js/ files; here every chunk, stylesheet and document in the
        # export is read, and only the generated worker is allowed to carry it.
        leaked = []
        for dirpath, _dirs, names in os.walk(OUT):
            for n in names:
                f = os.path.join(dirpath, n)
                rel = os.path.relpath(f, OUT).replace(os.sep, '/')
                if rel == 'sw.js' or not n.endswith(('.js', '.css', '.html', '.txt', '.json')):
                    continue
                try:
                    src = open(f, encoding='utf-8', errors='ignore').read()
                except OSError:
                    continue
                if re.search(r'zajil-v\d+\.\d+\.\d+', src):
                    leaked.append(rel)
        check('no shipped file hardcodes an app version string — only the worker carries it',
              leaked == [], str(leaked[:4]))

        # graceful fallback where there is no service worker at all
        ctx2 = br.new_context()
        p2 = ctx2.new_page()
        p2.add_init_script("Object.defineProperty(navigator, 'serviceWorker', { get: () => undefined });")
        p2.goto(ROOT + 'tools.html', wait_until='load'); p2.wait_for_timeout(2500)
        fb = p2.locator('[data-testid=about-version]')
        check('without a service worker the row still renders', fb.count() == 1)
        check('…showing the unknown fallback, not a blank', 'غير معروف' in fb.inner_text(), fb.inner_text())
        ctx2.close()

        check('zero page errors', not errs, '; '.join(errs[:2]))
        br.close()
finally:
    srv.terminate()

print(f'\n{ok} passed, {fail} failed')
raise SystemExit(1 if fail else 0)
